security:
  jwt:
    token:
      issuer: projeto-pessoal-api
      secret-key: ${SECRET_KEY}
      secret-password: ${SECRET_PASSWORD}
      expire-lenght: 3600000
spring:
  application:
    name: Projeto Pessoal
  profiles:
    active: dev
spring-doc:
  paths-to-match:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true

