cors:
  originPatterns: http://hml-origem.exemplo.com
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL_HML}
    username: ${DB_USER_HML}
    password: ${DB_PASSWORD_HML}
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    root: INFO
    br.com.seuprojeto: INFO
    org.hibernate.SQL: INFO     # Apenas informa que houve uma query, sem o detalhamento


